In [1]:
import pandas as pd
import numpy as np

In [2]:
GDP_MidEast = pd.read_excel("Data/mideast.xlsx")
MidEast_df= pd.DataFrame(GDP_MidEast)
MidEast_df.drop(MidEast_df.columns[MidEast_df.columns.str.contains(
    'unnamed', case=False)], axis=1, inplace=True)
MidEast_df

,Country,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,Average Difference 2019 to 2022
0,Afghanistan,1.350055,0.743824,1.627064,1.430659,2.237212,2.209413,2.246572,NaN,NaN,NaN,1.313
1,Algeria,-9.435627,-27.289577,-26.473435,-22.330869,-16.883755,-16.910938,-18.681438,-4.511992,19.063897,6.532556,NaN
2,Armenia,-0.899770,-0.280870,-0.100910,-0.145340,-0.900500,-0.961090,-0.505370,-0.482960,0.151040,-0.333195,NaN
3,Azerbaijan,10.430530,-0.222495,-1.363404,1.684559,6.051077,4.364886,-0.227568,8.291580,23.478081,12.642864,NaN
4,Bahrain,1.523138,-0.752128,-1.492819,-1.450000,-2.434574,-0.794149,-3.244681,2.602394,6.838564,2.986680,NaN
5,Djibouti,0.530582,0.714225,-0.026059,-0.132469,0.428623,0.563970,0.366363,0.087367,-0.176198,-0.124573,NaN
6,Egypt,-2.746400,-12.142600,-19.831100,-14.394000,-5.962300,-10.893900,-11.166700,-18.436400,-16.551300,-6.810728,NaN
7,Georgia,-1.784183,-1.767022,-1.885854,-1.308248,-1.192211,-1.024538,-1.980623,-1.937421,-0.978765,-1.821323,NaN
8,"Iran, Islamic Republic of",13.572000,1.235000,13.236000,14.915000,26.242000,-1.651000,-0.707000,11.145000,14.433000,12.594473,NaN
9,Iraq,6.106320,-12.348763,-13.314777,-10.211871,8.839738,-1.678080,-27.192685,14.184539,45.047645,-4.944264,NaN
10,Jordan,-2.612248,-3.474312,-3.856800,-4.398731,-2.966714,-0.773907,-2.508463,-3.722849,-4.165021,-3.778504,NaN
11,Kazakhstan,-2.852800,-9.979400,-6.964600,-3.426400,-1.765600,-7.028200,-10.961500,-2.558800,7.816300,-3.933376,NaN
12,Kuwait,54.402775,4.012644,-5.060261,9.609362,19.894901,17.861485,4.852641,37.387494,63.167005,48.414874,NaN
13,Kyrgyz Republic,-1.269398,-1.058599,-0.791996,-0.477386,-0.996963,-1.073258,0.374089,-0.739000,-5.426814,-2.533933,NaN
14,Lebanon,-13.883348,-9.917536,-12.041738,-13.990187,-15.724880,-14.203330,-3.847723,-3.532428,-6.270874,NaN,NaN
15,Libya,-18.997540,-9.204841,-4.704084,4.413910,11.274045,4.641804,-3.976359,-1.896369,12.422050,8.544157,NaN
16,Mauritania,-1.470718,-0.956128,-0.706781,-0.681043,-0.975616,-0.831134,-0.576304,-0.773531,-1.518397,-1.022929,NaN
17,Morocco,-6.568819,-2.165449,-4.184522,-3.749650,-6.218524,-4.410727,-1.414838,-3.329594,-4.622042,-4.515730,NaN
18,Oman,4.206338,-10.939016,-12.539505,-10.826441,-4.203175,-4.055452,-12.263027,-4.783482,7.349016,5.511816,NaN
19,Pakistan,-3.130000,-2.815000,-4.961000,-12.270000,-19.195000,-13.434000,-4.449000,-2.820000,-17.481000,NaN,NaN
20,Qatar,49.409890,13.750824,-8.269505,6.425549,16.652198,4.259890,-2.985714,26.319231,63.117857,41.529243,NaN
21,Saudi Arabia,73.758300,-56.723900,-23.842700,10.464100,71.971700,38.229800,-22.814000,44.323500,150.753200,63.591420,NaN
22,Somalia,-0.149091,-0.149119,-0.416959,0.131727,-0.009543,-0.851235,-0.417164,-0.682483,-0.850658,-1.107484,NaN
23,Sudan,-3.545467,-5.460760,-4.213357,-4.611259,-4.678502,-4.779839,-5.841224,-2.620163,-3.794130,-0.243282,NaN
24,Tajikistan,-0.316455,-0.477075,-0.290827,0.158969,-0.379682,-0.185295,0.335906,0.734735,1.634601,-0.435148,NaN
25,Tunisia,-4.688967,-4.185850,-3.892555,-4.080076,-4.443482,-3.273747,-2.506329,-2.781241,-3.984282,-2.959600,NaN
26,Turkmenistan,-4.341790,-7.614040,-9.635373,-5.144574,2.408552,1.468552,1.377160,4.202530,5.478947,2.771241,NaN
27,United Arab Emirates,54.491144,17.550895,13.200136,27.500163,41.242398,37.320626,21.102791,47.950987,59.547056,41.566932,NaN
28,Uzbekistan,2.075923,0.895642,0.213236,1.477884,-3.593174,-3.371224,-3.027885,-4.894553,-0.618028,-3.859714,NaN
29,West Bank and Gaza,-1.900700,-1.939200,-2.142500,-2.130000,-2.140400,-1.779300,-1.902700,-1.777900,-2.865500,-2.650498,NaN
30,"Yemen, Republic of",0.568617,-1.330155,-1.829439,-0.627918,-1.164645,-1.324926,-3.442229,-2.972298,-4.196486,-4.088741,NaN

In [4]:
MidEast_df.mean(axis=1)

C:\Users\ridhw\AppData\Local\Temp\ipykernel_22640\3318831720.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  MidEast_df.mean(axis=1)

0      1.644725
1    -11.692118
2     -0.445897
3      6.513011
4      0.378242
5      0.223183
6    -11.893543
7     -1.568019
8     10.501447
9      0.448780
10    -3.225755
11    -4.165438
12    25.454292
13    -1.399326
14   -10.379116
15     0.251677
16    -0.951258
17    -4.117989
18    -4.254293
19    -8.950556
20    21.020946
21    34.971142
22    -0.450201
23    -3.978798
24     0.077973
25    -3.679613
26    -0.902879
27    36.147313
28    -1.470189
29    -2.122870
30    -2.040822
dtype: float64

In [3]:
mideast_future= pd.read_csv("Data/mideast_future.csv")
mideast_future

,Country,2024,2025,2026,2027,2028
0,Afghanistan,-24.979520,-24.784130,-32.541562,-42.727071,-56.100645
1,Algeria,-21.300030,-20.481760,-26.892550,-35.309919,-46.361923
2,Armenia,-13.973176,-13.145082,-17.259493,-22.661714,-29.754831
3,Azerbaijan,-29.741613,-28.006163,-36.772092,-48.281756,-63.393946
4,Bahrain,-9.090654,-9.131612,-11.989807,-15.742617,-20.670056
5,Djibouti,-32.567650,-31.251833,-41.033657,-53.877192,-70.740753
6,Egypt,-6.825795,-7.006382,-9.199380,-12.078786,-15.859446
7,Georgia,-3.029879,-3.038889,-3.990061,-5.238950,-6.878742
8,"Iran, Islamic Republic of",-28.707308,-27.537731,-36.157041,-47.474195,-62.333618
9,Iraq,2.293038,2.661287,3.494270,4.587976,6.024013
10,Jordan,0.896197,0.550909,0.723344,0.949750,1.247022
11,Kazakhstan,-3.036523,-3.405188,-4.471012,-5.870439,-7.707886
12,Kuwait,-7.629789,-6.747909,-8.860005,-11.633187,-15.274374
13,Kyrgyz Republic,-4.360342,-4.335383,-5.692357,-7.474065,-9.813448
14,Lebanon,-0.128550,0.011971,0.015718,0.020638,0.027098
15,Libya,-8.510479,-7.834826,-10.287126,-13.506996,-17.734686
16,Mauritania,-2.530205,-1.944148,-2.552666,-3.351651,-4.400718
17,Morocco,-2.456175,-2.300000,-3.019900,-3.965129,-5.206214
18,Oman,-2.757446,-1.626467,-2.135552,-2.803979,-3.681625
19,Pakistan,-0.465158,-1.311430,-1.721907,-2.260864,-2.968515
20,Qatar,-2.092544,-1.934028,-2.539379,-3.334204,-4.377810
21,Saudi Arabia,-1.103154,-1.866334,-2.450497,-3.217503,-4.224581
22,Somalia,-7.667649,-5.305815,-6.966536,-9.147061,-12.010091
23,Sudan,-1.675288,-1.263955,-1.659573,-2.179019,-2.861052
24,Tajikistan,27.286220,28.087198,36.878490,48.421458,63.577374
25,Tunisia,5.069019,4.702166,6.173944,8.106388,10.643688
26,Turkmenistan,-2.503379,-2.476949,-3.252234,-4.270184,-5.606751
27,United Arab Emirates,-4.288036,-3.783538,-4.967786,-6.522703,-8.564309
28,Uzbekistan,-3.010922,-2.594503,-3.406582,-4.472842,-5.872842
29,West Bank and Gaza,-7.598340,-8.799656,-11.553949,-15.170335,-19.918649
30,"Yemen, Republic of",-7.392464,-7.260368,-9.532864,-12.516650,-16.434361