In [1]:
import pandas as pd
import numpy as np

In [2]:
GDP_West = pd.read_excel("Data/west.xlsx")
West_df= pd.DataFrame(GDP_West)
West_df.drop(West_df.columns[West_df.columns.str.contains(
    'unnamed', case=False)], axis=1, inplace=True)
West_df

,Country,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Canada,2.870,0.659,1.001,3.040,2.777,1.888,-5.074,5.012,3.438,1.292
1,Mexico,2.504,2.702,1.772,1.872,1.972,-0.278,-8.652,5.838,3.898,3.177
2,Puerto Rico,-1.190,-1.049,-1.263,-2.886,-4.364,1.679,-4.352,0.206,2.000,-0.700
3,United States,2.288,2.707,1.668,2.242,2.945,2.295,-2.768,5.947,2.062,2.085
4,Argentina,-2.513,2.731,-2.080,2.819,-2.617,-2.001,-9.900,10.718,4.956,-2.500
5,Bolivia,5.461,4.857,4.264,4.195,4.224,2.217,-8.738,6.106,3.478,1.800
6,Brazil,0.504,-3.546,-3.276,1.323,1.784,1.221,-3.277,4.989,2.901,3.084
7,Chile,1.793,2.152,1.753,1.358,3.990,0.743,-6.145,11.737,2.440,-0.532
8,Colombia,4.499,2.956,2.087,1.359,2.565,3.187,-7.252,11.016,7.257,1.442
9,Ecuador,3.789,0.099,-1.226,2.368,1.289,0.012,-7.788,4.235,2.948,1.372
10,Paraguay,5.301,2.957,4.268,4.810,3.204,-0.402,-0.820,4.017,0.075,4.477
11,Peru,2.384,3.252,3.954,2.522,3.970,2.240,-10.953,13.350,2.683,1.130
12,Uruguay,3.239,0.371,1.690,1.740,0.156,0.744,-6.263,5.277,4.922,0.999
13,Venezuela,-3.894,-6.221,-17.040,-15.671,-19.655,-27.670,-29.995,1.000,8.000,4.000
14,Costa Rica,3.542,3.652,4.204,4.158,2.616,2.418,-4.273,7.781,4.305,4.415
15,Dominican Republic,7.050,6.927,6.659,4.667,6.983,5.052,-6.720,12.272,4.858,2.966
16,El Salvador,1.704,2.400,2.515,2.262,2.422,2.456,-7.878,11.178,2.600,2.200
17,Guatemala,4.444,4.092,2.678,3.080,3.407,4.018,-1.792,8.002,4.118,3.432
18,Honduras,3.058,3.840,3.893,4.843,3.845,2.653,-8.965,12.534,4.000,2.900
19,Nicaragua,4.785,4.792,4.798,4.396,-3.363,-2.897,-1.766,10.347,3.751,3.024
20,Panama,5.067,5.733,4.953,5.591,3.685,3.282,-17.668,15.836,10.809,6.000
21,Antigua and Barbuda,3.797,3.824,5.497,3.144,6.824,4.344,-17.503,6.556,8.459,5.592
22,Aruba,-0.015,3.551,2.110,0.732,2.382,-2.303,-23.983,27.639,10.458,2.300
23,"Bahamas, The",1.847,0.997,-0.763,2.524,2.918,-0.744,-23.508,16.985,14.369,4.306
24,Barbados,-0.126,2.446,2.485,0.478,-0.583,-0.523,-13.311,-0.189,9.800,4.500
25,Belize,4.088,3.371,0.120,-1.712,1.123,4.492,-13.392,15.208,12.726,4.007
26,Dominica,4.754,-2.732,2.764,-6.619,3.548,5.502,-16.605,6.892,5.711,4.624
27,Grenada,7.342,6.445,3.740,4.439,4.361,0.677,-13.757,4.689,6.354,3.870
28,Jamaica,0.575,0.869,1.498,0.679,1.827,0.970,-9.920,4.601,5.222,2.000
29,St. Kitts and Nevis,7.587,0.717,3.910,0.017,2.053,4.050,-14.561,-0.891,8.823,4.899
30,St. Lucia,1.303,-0.240,3.805,3.379,2.861,-0.200,-23.586,11.315,15.674,3.225
31,St. Vincent and the Grenadines,1.146,2.785,4.150,1.548,3.175,0.662,-3.739,0.754,5.500,6.230
32,Haiti,1.723,2.563,1.812,2.510,1.668,-1.685,-3.343,-1.798,-1.682,-1.500
33,Guyana,1.686,0.687,3.807,3.734,4.441,5.353,43.480,20.060,62.288,38.432
34,Suriname,0.254,-3.414,-4.912,1.566,4.948,1.098,-15.906,-2.742,1.028,2.148
35,Trinidad and Tobago,3.936,0.978,-7.527,-4.801,-0.602,0.361,-9.078,-1.037,1.482,2.507

In [4]:
West_df.mean(axis=1)

C:\Users\ridhw\AppData\Local\Temp\ipykernel_11612\1784674342.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  West_df.mean(axis=1)

0      1.6903
1      1.4805
2     -1.1919
3      2.1471
4     -0.0387
5      2.7864
6      0.5707
7      1.9289
8      2.9116
9      0.7098
10     2.7887
11     2.4532
12     1.2875
13   -10.7146
14     3.2818
15     5.0714
16     2.1859
17     3.5479
18     3.2601
19     2.7867
20     4.3288
21     3.0534
22     2.2871
23     1.8931
24     0.4977
25     3.0031
26     0.7839
27     2.8160
28     0.8321
29     1.6604
30     1.7536
31     2.2211
32     0.0268
33    18.3968
34    -1.5932
35    -1.3781
dtype: float64

In [3]:
west_future= pd.read_csv("Data/west_future.csv")
west_future

                           Country      2024     2025  2026  2027  2028
0                           Canada   5.76500  5.50900  2.79  1.42  0.72
1                           Mexico   6.38000  7.71000  3.91  1.98  1.00
2                      Puerto Rico   2.68000  2.75000  1.39  0.71  0.36
3                    United States   1.36700  1.54800  0.78  0.40  0.20
4                        Argentina   6.60000  6.50000  3.30  1.67  0.85
5                          Bolivia   8.28900  9.28100  4.71  2.39  1.21
6                           Brazil   6.76300  6.35500  3.22  1.63  0.83
7                            Chile   3.06300  2.25400  1.14  0.58  0.29
8                         Colombia   2.02000  2.11000  1.07  0.54  0.27
9                          Ecuador   2.50000  2.63000  1.33  0.68  0.34
10                        Paraguay   8.00000  7.50000  3.80  1.93  0.98
11                            Peru   5.99500  5.99500  3.04  1.54  0.78
12                         Uruguay   4.11300  3.03900  1.54  0.78  0.40
13                       Venezuela   5.00000  4.00000  2.03  1.03  0.52
14                      Costa Rica   8.79000  8.89000  4.51  2.29  1.16
15              Dominican Republic   7.00000  5.00000  2.54  1.29  0.65
16                     El Salvador   1.22000  1.28000  0.65  0.33  0.17
17                       Guatemala   0.89600  1.70000  0.86  0.44  0.22
18                        Honduras  16.71600  7.65600  3.88  1.97  1.00
19                       Nicaragua   2.47000  2.57000  1.30  0.66  0.33
20                          Panama   4.20000  4.00000  2.03  1.03  0.52
21             Antigua and Barbuda   3.40000  3.40000  1.72  0.87  0.44
22                           Aruba   3.18000  3.00000  1.52  0.77  0.39
23                    Bahamas, The   1.14000  1.21000  0.61  0.31  0.16
24                        Barbados   2.80800  2.08300  1.06  0.54  0.27
25                          Belize   5.00000  5.05000  2.56  1.30  0.66
26                        Dominica   6.00000  6.00000  3.04  1.54  0.78
27                         Grenada   8.00500  8.00000  4.06  2.06  1.04
28                         Jamaica   2.82900  2.99500  1.52  0.77  0.39
29             St. Kitts and Nevis   1.70900  2.01800  1.02  0.52  0.26
30                       St. Lucia   8.03200  7.88400  4.00  2.03  1.03
31  St. Vincent and the Grenadines   1.86000  1.97300  1.00  0.51  0.26
32                           Haiti   6.32300  6.25500  3.17  1.61  0.82
33                          Guyana   2.13276  2.25069  1.14  0.58  0.29
34                        Suriname   2.60600  1.85400  0.94  0.48  0.24
35             Trinidad and Tobago   6.67700  6.55200  3.32  1.68  0.85