In [1]:
import pandas as pd
import numpy as np
import random
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
#Loading Africa Data from 2014 - 2015, single file did not have these years so it will need to be merged
africa_1 = pd.read_excel("Data/africa_1.xlsx")
africa_1

                 Country      2014       2015
0                 Angola  7.298250   9.159489
1               Benin /1 -1.066813   0.202132
2               Botswana  4.414625   3.054161
3        Burkina Faso /1 -0.258043   1.653333
4                Burundi  4.416834   5.553870
..                   ...       ...        ...
59  COMESA (SSA members)  0.186919   1.789864
60                EAC -5  4.290111   3.692463
61                ECOWAS -0.097138   1.114015
62                  SACU  7.810685  10.106702
63                  SADC -0.212940  -2.409555

[64 rows x 3 columns]

In [3]:
#Loading Africa Data from 2016 - 2023
africa_2 = pd.read_excel("Data/africa_2.xlsx")
africa_2

,Country,2016,Unnamed: 2,2017,Unnamed: 4,2018,Unnamed: 6,2019,Unnamed: 8,2020,Unnamed: 10,2021,Unnamed: 12,2022,Unnamed: 14,2023
0,Angola,-6.011877,NaN,-3.633446,NaN,-4.676609,NaN,-4.017052,NaN,-8.672491,NaN,-1.954664,NaN,-0.438961,NaN,-1.694201
1,Benin /1,0.335852,NaN,2.603557,NaN,3.624263,NaN,3.824507,NaN,0.951938,NaN,4.129264,NaN,3.319873,NaN,2.587637
2,Botswana,5.048820,NaN,1.970664,NaN,2.083051,NaN,1.042060,NaN,-10.400330,NaN,10.050526,NaN,4.098347,NaN,2.092020
3,Burkina Faso /1,2.893498,NaN,3.203257,NaN,3.692238,NaN,2.869545,NaN,-0.852021,NaN,3.985314,NaN,-1.290476,NaN,1.520630
4,Burundi,-3.682189,NaN,-2.616273,NaN,-1.349596,NaN,-1.123816,NaN,-2.587287,NaN,0.115828,NaN,-1.139028,NaN,0.326282
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,COMESA (SSA members),1.544123,NaN,3.048263,NaN,3.303130,NaN,3.140596,NaN,-2.039112,NaN,3.989740,NaN,3.566515,NaN,3.006656
60,EAC -5,1.463521,NaN,2.358207,NaN,3.389089,NaN,3.532307,NaN,-1.846960,NaN,3.973809,NaN,2.753798,NaN,2.558003
61,ECOWAS,-1.825906,NaN,0.325335,NaN,0.653526,NaN,0.954235,NaN,-3.132111,NaN,1.802011,NaN,1.286668,NaN,0.741513
62,SACU,-0.598226,NaN,-0.320437,NaN,0.141713,NaN,-1.090083,NaN,-7.422353,NaN,4.032144,NaN,1.329446,NaN,-0.375026
63,SADC,-0.867926,NaN,-0.122194,NaN,0.124224,NaN,-0.803188,NaN,-6.190303,NaN,2.698348,NaN,1.588482,NaN,0.359180

In [4]:
#In order to merge both tables need to be dataframes using Pandas
africa_1df= pd.DataFrame(africa_1)
africa_2df= pd.DataFrame(africa_2)
#from africa 2 I have to remove the unamed columns
africa_2df.drop(africa_2df.columns[africa_2df.columns.str.contains(
    'unnamed', case=False)], axis=1, inplace=True)
africa_2df

,Country,2016,2017,2018,2019,2020,2021,2022,2023
0,Angola,-6.011877,-3.633446,-4.676609,-4.017052,-8.672491,-1.954664,-0.438961,-1.694201
1,Benin /1,0.335852,2.603557,3.624263,3.824507,0.951938,4.129264,3.319873,2.587637
2,Botswana,5.048820,1.970664,2.083051,1.042060,-10.400330,10.050526,4.098347,2.092020
3,Burkina Faso /1,2.893498,3.203257,3.692238,2.869545,-0.852021,3.985314,-1.290476,1.520630
4,Burundi,-3.682189,-2.616273,-1.349596,-1.123816,-2.587287,0.115828,-1.139028,0.326282
...,...,...,...,...,...,...,...,...,...
59,COMESA (SSA members),1.544123,3.048263,3.303130,3.140596,-2.039112,3.989740,3.566515,3.006656
60,EAC -5,1.463521,2.358207,3.389089,3.532307,-1.846960,3.973809,2.753798,2.558003
61,ECOWAS,-1.825906,0.325335,0.653526,0.954235,-3.132111,1.802011,1.286668,0.741513
62,SACU,-0.598226,-0.320437,0.141713,-1.090083,-7.422353,4.032144,1.329446,-0.375026
63,SADC,-0.867926,-0.122194,0.124224,-0.803188,-6.190303,2.698348,1.588482,0.359180

In [5]:
#now I merge both dataframes into 1 dataframe using merge function
africa_df= africa_1df.merge(africa_2df)
africa_df

,Country,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Angola,7.298250,9.159489,-6.011877,-3.633446,-4.676609,-4.017052,-8.672491,-1.954664,-0.438961,-1.694201
1,Benin /1,-1.066813,0.202132,0.335852,2.603557,3.624263,3.824507,0.951938,4.129264,3.319873,2.587637
2,Botswana,4.414625,3.054161,5.048820,1.970664,2.083051,1.042060,-10.400330,10.050526,4.098347,2.092020
3,Burkina Faso /1,-0.258043,1.653333,2.893498,3.203257,3.692238,2.869545,-0.852021,3.985314,-1.290476,1.520630
4,Burundi,4.416834,5.553870,-3.682189,-2.616273,-1.349596,-1.123816,-2.587287,0.115828,-1.139028,0.326282
...,...,...,...,...,...,...,...,...,...,...,...
59,COMESA (SSA members),0.186919,1.789864,1.544123,3.048263,3.303130,3.140596,-2.039112,3.989740,3.566515,3.006656
60,EAC -5,4.290111,3.692463,1.463521,2.358207,3.389089,3.532307,-1.846960,3.973809,2.753798,2.558003
61,ECOWAS,-0.097138,1.114015,-1.825906,0.325335,0.653526,0.954235,-3.132111,1.802011,1.286668,0.741513
62,SACU,7.810685,10.106702,-0.598226,-0.320437,0.141713,-1.090083,-7.422353,4.032144,1.329446,-0.375026
63,SADC,-0.212940,-2.409555,-0.867926,-0.122194,0.124224,-0.803188,-6.190303,2.698348,1.588482,0.359180

In [6]:
#The Same steps will apply for the other data
asia_1 = pd.read_excel("Data/asia_1.xlsx")
asia_2 = pd.read_excel("Data/asia_2.xlsx")
asia_1df= pd.DataFrame(asia_1)
asia_2df= pd.DataFrame(asia_2)
asia_2df.drop(asia_2df.columns[asia_2df.columns.str.contains(
    'unnamed', case=False)], axis=1, inplace=True)
asia_df= asia_1df.merge(asia_2df)
asia_df

,Country,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Australia,30.709187,16.679041,12.893905,16.362220,2.815073,1.947896,-1.830124,5.206418,3.691769,1.777237
1,Bangladesh,-2.409839,-2.211401,-1.981427,-2.446321,7.319412,7.881873,3.448054,6.938679,7.099829,6.025446
2,Bhutan,0.984469,3.134047,3.435158,4.177681,3.835341,4.425452,-2.347745,-3.332399,4.757222,5.327911
3,Brunei Darussalam,0.296187,1.560646,0.753845,1.675313,0.052371,3.868844,1.133573,-1.590762,-1.628319,-0.768429
4,Cambodia,-0.481515,-33.661112,29.885092,2.072881,7.469169,7.054107,-3.096007,3.026389,5.238913,5.647004
5,"China, P.R.: Hong Kong",75.577418,12.770503,-32.986633,-17.768047,2.846921,-1.672432,-6.544799,6.441724,-3.476330,4.393917
6,"China, P.R.: Macao",-1.163257,2.099756,2.146024,3.734775,6.464503,-2.511843,-54.235915,19.267158,-26.760990,74.400000
7,"China, P.R.: Mainland",0.596953,-0.859423,1.124871,0.775589,6.750863,5.950966,2.242039,8.449611,2.988781,5.010125
8,Fiji,5.296087,-0.569085,0.496591,0.502513,3.812351,-0.580504,-17.039871,-4.881036,20.016464,7.458878
9,India,5.520352,0.339546,-0.532149,3.710089,6.453839,3.871461,-5.831035,9.050260,7.239727,6.331976
10,Indonesia,-1.528642,-1.028087,2.777383,0.388395,5.174292,5.019288,-2.065512,3.703055,5.308595,4.971284
11,Japan,2.080025,1.595813,1.601968,1.343541,0.643409,-0.402187,-4.242172,2.229917,1.046674,1.956583
12,Kiribati,5.389870,3.251851,3.899205,5.264212,5.278832,-2.145676,-1.384183,7.886343,1.153888,2.577077
13,"Korea, Republic of",2.701631,4.284838,6.100536,5.026871,2.907409,2.243972,-0.709415,4.304740,2.612667,1.445190
14,Lao People's Democratic Republic,3.613033,3.471709,3.851238,3.920415,6.289033,4.652000,-0.434963,2.061387,2.252135,3.967024
15,Malaysia,5.700533,3.417884,-0.471182,7.731269,4.843139,4.413220,-5.456855,3.297681,8.650309,3.960239
16,Maldives,-3.754994,-2.697489,-3.534762,-4.274750,8.123129,6.883689,-33.360519,41.746623,13.863351,8.068151
17,"Marshall Islands, Republic of",1.667357,9.378884,4.745848,3.279593,5.656071,10.313741,-2.901397,1.028199,-4.453561,3.000000
18,"Micronesia, Federated States of",1.894289,-0.899442,0.188193,0.665124,0.211658,1.200000,-2.806571,-2.188526,-0.555713,2.603351
19,Mongolia,1.541624,1.675664,2.101537,1.679125,7.744881,5.602245,-4.557752,1.636770,5.032710,5.500000
20,Myanmar,5.593145,7.170246,6.531025,4.635087,6.404977,6.750460,3.189416,-17.937795,1.970960,2.582971
21,Nepal,3.491667,3.591667,3.675000,3.683333,7.622376,6.657056,-2.369621,4.838150,5.613193,0.771913
22,New Zealand,3.202454,2.809103,2.946882,3.159636,3.524238,3.071752,-1.464442,6.058741,2.651777,1.120599
23,Palau,5.593674,3.733480,1.443890,2.040816,1.260919,1.357494,-7.040133,-13.362077,-1.964304,0.800000
24,Papua New Guinea,-2.048309,-21.514210,-0.679240,9.983387,-0.279252,4.480464,-3.167385,0.069587,4.347708,3.048495
25,Philippines,6.048235,4.560563,2.368957,1.228124,6.341490,6.118518,-9.518303,5.714728,7.570349,5.320657
26,Samoa,32.705733,23.342457,26.523508,30.768309,-0.609646,4.451859,-3.108586,-7.078696,-5.309638,8.010610
27,Singapore,1.700000,1.825000,1.900000,1.975000,3.575433,1.331261,-3.901053,8.882354,3.646972,1.040000
28,Solomon Islands,-6.467066,-22.800464,-0.386622,8.602490,2.744968,1.748550,-3.381858,-0.565230,-4.070833,2.506440
29,Sri Lanka,2.512684,1.484798,1.277288,1.994955,2.310064,-0.220476,-4.624506,3.512216,-7.823977,NaN
30,Taiwan Province of China,-1.313700,-1.049921,-0.625371,-1.835281,2.786770,3.063950,3.386636,6.527663,2.354238,0.842569
31,Thailand,3.136867,0.366522,4.688756,6.317305,4.222870,2.114558,-6.066926,1.468492,2.643322,2.700006
32,"Timor-Leste, Dem. Rep. of",8.083990,7.576493,10.439292,2.710843,-0.689947,2.081484,-8.282002,2.852567,3.900000,1.500000
33,Tonga,-3.536386,-1.564410,-3.600463,-0.844233,0.241224,0.706463,0.488649,-2.667490,-1.961778,2.558116
34,Tuvalu,4.720266,4.745117,5.372868,5.247526,1.387251,13.821984,-4.274832,1.804062,0.677335,3.852801
35,Vanuatu,2.540585,1.692111,7.121812,3.413242,2.900230,3.241188,-4.992491,0.648123,1.850101,1.483511
36,Vietnam,0.464307,1.674222,0.767667,1.847050,7.465007,7.359263,2.867221,2.559762,8.019792,4.700000

In [7]:
#GDP Middle East Data
GDP_MidEast = pd.read_excel("Data/GDP_MidEast.xlsx")
MidEast_df= pd.DataFrame(GDP_MidEast)
MidEast_df.drop(MidEast_df.columns[MidEast_df.columns.str.contains(
    'unnamed', case=False)], axis=1, inplace=True)
MidEast_df

,Country,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,1.350055,0.743824,1.627064,1.430659,2.237212,2.209413,2.246572,NaN,NaN,NaN
1,Algeria,-9.435627,-27.289577,-26.473435,-22.330869,-16.883755,-16.910938,-18.681438,-4.511992,19.063897,6.532556
2,Armenia,-0.899770,-0.280870,-0.100910,-0.145340,-0.900500,-0.961090,-0.505370,-0.482960,0.151040,-0.333195
3,Azerbaijan,10.430530,-0.222495,-1.363404,1.684559,6.051077,4.364886,-0.227568,8.291580,23.478081,12.642864
4,Bahrain,1.523138,-0.752128,-1.492819,-1.450000,-2.434574,-0.794149,-3.244681,2.602394,6.838564,2.986680
5,Djibouti,0.530582,0.714225,-0.026059,-0.132469,0.428623,0.563970,0.366363,0.087367,-0.176198,-0.124573
6,Egypt,-2.746400,-12.142600,-19.831100,-14.394000,-5.962300,-10.893900,-11.166700,-18.436400,-16.551300,-6.810728
7,Georgia,-1.784183,-1.767022,-1.885854,-1.308248,-1.192211,-1.024538,-1.980623,-1.937421,-0.978765,-1.821323
8,"Iran, Islamic Republic of",13.572000,1.235000,13.236000,14.915000,26.242000,-1.651000,-0.707000,11.145000,14.433000,12.594473
9,Iraq,6.106320,-12.348763,-13.314777,-10.211871,8.839738,-1.678080,-27.192685,14.184539,45.047645,-4.944264
10,Jordan,-2.612248,-3.474312,-3.856800,-4.398731,-2.966714,-0.773907,-2.508463,-3.722849,-4.165021,-3.778504
11,Kazakhstan,-2.852800,-9.979400,-6.964600,-3.426400,-1.765600,-7.028200,-10.961500,-2.558800,7.816300,-3.933376
12,Kuwait,54.402775,4.012644,-5.060261,9.609362,19.894901,17.861485,4.852641,37.387494,63.167005,48.414874
13,Kyrgyz Republic,-1.269398,-1.058599,-0.791996,-0.477386,-0.996963,-1.073258,0.374089,-0.739000,-5.426814,-2.533933
14,Lebanon,-13.883348,-9.917536,-12.041738,-13.990187,-15.724880,-14.203330,-3.847723,-3.532428,-6.270874,NaN
15,Libya,-18.997540,-9.204841,-4.704084,4.413910,11.274045,4.641804,-3.976359,-1.896369,12.422050,8.544157
16,Mauritania,-1.470718,-0.956128,-0.706781,-0.681043,-0.975616,-0.831134,-0.576304,-0.773531,-1.518397,-1.022929
17,Morocco,-6.568819,-2.165449,-4.184522,-3.749650,-6.218524,-4.410727,-1.414838,-3.329594,-4.622042,-4.515730
18,Oman,4.206338,-10.939016,-12.539505,-10.826441,-4.203175,-4.055452,-12.263027,-4.783482,7.349016,5.511816
19,Pakistan,-3.130000,-2.815000,-4.961000,-12.270000,-19.195000,-13.434000,-4.449000,-2.820000,-17.481000,NaN
20,Qatar,49.409890,13.750824,-8.269505,6.425549,16.652198,4.259890,-2.985714,26.319231,63.117857,41.529243
21,Saudi Arabia,73.758300,-56.723900,-23.842700,10.464100,71.971700,38.229800,-22.814000,44.323500,150.753200,63.591420
22,Somalia,-0.149091,-0.149119,-0.416959,0.131727,-0.009543,-0.851235,-0.417164,-0.682483,-0.850658,-1.107484
23,Sudan,-3.545467,-5.460760,-4.213357,-4.611259,-4.678502,-4.779839,-5.841224,-2.620163,-3.794130,-0.243282
24,Tajikistan,-0.316455,-0.477075,-0.290827,0.158969,-0.379682,-0.185295,0.335906,0.734735,1.634601,-0.435148
25,Tunisia,-4.688967,-4.185850,-3.892555,-4.080076,-4.443482,-3.273747,-2.506329,-2.781241,-3.984282,-2.959600
26,Turkmenistan,-4.341790,-7.614040,-9.635373,-5.144574,2.408552,1.468552,1.377160,4.202530,5.478947,2.771241
27,United Arab Emirates,54.491144,17.550895,13.200136,27.500163,41.242398,37.320626,21.102791,47.950987,59.547056,41.566932
28,Uzbekistan,2.075923,0.895642,0.213236,1.477884,-3.593174,-3.371224,-3.027885,-4.894553,-0.618028,-3.859714
29,West Bank and Gaza,-1.900700,-1.939200,-2.142500,-2.130000,-2.140400,-1.779300,-1.902700,-1.777900,-2.865500,-2.650498
30,"Yemen, Republic of",0.568617,-1.330155,-1.829439,-0.627918,-1.164645,-1.324926,-3.442229,-2.972298,-4.196486,-4.088741

In [8]:
#GDP Western Country GDP
GDP_West = pd.read_excel("Data/GDP_West.xlsx")
West_df= pd.DataFrame(GDP_West)
West_df.drop(West_df.columns[West_df.columns.str.contains(
    'unnamed', case=False)], axis=1, inplace=True)
West_df

,Country,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Canada,2.870,0.659,1.001,3.040,2.777,1.888,-5.074,5.012,3.438,1.292
1,Mexico,2.504,2.702,1.772,1.872,1.972,-0.278,-8.652,5.838,3.898,3.177
2,Puerto Rico,-1.190,-1.049,-1.263,-2.886,-4.364,1.679,-4.352,0.206,2.000,-0.700
3,United States,2.288,2.707,1.668,2.242,2.945,2.295,-2.768,5.947,2.062,2.085
4,Argentina,-2.513,2.731,-2.080,2.819,-2.617,-2.001,-9.900,10.718,4.956,-2.500
5,Bolivia,5.461,4.857,4.264,4.195,4.224,2.217,-8.738,6.106,3.478,1.800
6,Brazil,0.504,-3.546,-3.276,1.323,1.784,1.221,-3.277,4.989,2.901,3.084
7,Chile,1.793,2.152,1.753,1.358,3.990,0.743,-6.145,11.737,2.440,-0.532
8,Colombia,4.499,2.956,2.087,1.359,2.565,3.187,-7.252,11.016,7.257,1.442
9,Ecuador,3.789,0.099,-1.226,2.368,1.289,0.012,-7.788,4.235,2.948,1.372
10,Paraguay,5.301,2.957,4.268,4.810,3.204,-0.402,-0.820,4.017,0.075,4.477
11,Peru,2.384,3.252,3.954,2.522,3.970,2.240,-10.953,13.350,2.683,1.130
12,Uruguay,3.239,0.371,1.690,1.740,0.156,0.744,-6.263,5.277,4.922,0.999
13,Venezuela,-3.894,-6.221,-17.040,-15.671,-19.655,-27.670,-29.995,1.000,8.000,4.000
14,Costa Rica,3.542,3.652,4.204,4.158,2.616,2.418,-4.273,7.781,4.305,4.415
15,Dominican Republic,7.050,6.927,6.659,4.667,6.983,5.052,-6.720,12.272,4.858,2.966
16,El Salvador,1.704,2.400,2.515,2.262,2.422,2.456,-7.878,11.178,2.600,2.200
17,Guatemala,4.444,4.092,2.678,3.080,3.407,4.018,-1.792,8.002,4.118,3.432
18,Honduras,3.058,3.840,3.893,4.843,3.845,2.653,-8.965,12.534,4.000,2.900
19,Nicaragua,4.785,4.792,4.798,4.396,-3.363,-2.897,-1.766,10.347,3.751,3.024
20,Panama,5.067,5.733,4.953,5.591,3.685,3.282,-17.668,15.836,10.809,6.000
21,Antigua and Barbuda,3.797,3.824,5.497,3.144,6.824,4.344,-17.503,6.556,8.459,5.592
22,Aruba,-0.015,3.551,2.110,0.732,2.382,-2.303,-23.983,27.639,10.458,2.300
23,"Bahamas, The",1.847,0.997,-0.763,2.524,2.918,-0.744,-23.508,16.985,14.369,4.306
24,Barbados,-0.126,2.446,2.485,0.478,-0.583,-0.523,-13.311,-0.189,9.800,4.500
25,Belize,4.088,3.371,0.120,-1.712,1.123,4.492,-13.392,15.208,12.726,4.007
26,Dominica,4.754,-2.732,2.764,-6.619,3.548,5.502,-16.605,6.892,5.711,4.624
27,Grenada,7.342,6.445,3.740,4.439,4.361,0.677,-13.757,4.689,6.354,3.870
28,Jamaica,0.575,0.869,1.498,0.679,1.827,0.970,-9.920,4.601,5.222,2.000
29,St. Kitts and Nevis,7.587,0.717,3.910,0.017,2.053,4.050,-14.561,-0.891,8.823,4.899
30,St. Lucia,1.303,-0.240,3.805,3.379,2.861,-0.200,-23.586,11.315,15.674,3.225
31,St. Vincent and the Grenadines,1.146,2.785,4.150,1.548,3.175,0.662,-3.739,0.754,5.500,6.230
32,Haiti,1.723,2.563,1.812,2.510,1.668,-1.685,-3.343,-1.798,-1.682,-1.500
33,Guyana,1.686,0.687,3.807,3.734,4.441,5.353,43.480,20.060,62.288,38.432
34,Suriname,0.254,-3.414,-4.912,1.566,4.948,1.098,-15.906,-2.742,1.028,2.148
35,Trinidad and Tobago,3.936,0.978,-7.527,-4.801,-0.602,0.361,-9.078,-1.037,1.482,2.507

In [9]:
#africa scale test
random.seed(3277)

training, testing= train_test_split(africa_df)
print(training.shape)
print(testing.shape)

(48, 11)
(16, 11)

In [10]:
#africa regretion 
regr= linear_model.LinearRegression()
training_data= training.drop('2023', axis=1)
training_data= training_data.rename(str,axis="columns")
training_test= training.iloc[:, -1]
print(training_data.shape)
print(training_test.shape)

(48, 10)
(48,)

In [11]:
datafit= regr.fit(training_data, training_test)
training_data= testing.loc[:, ['2014', '2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']]
training_test= testing[['2013']].as_matrix()
prediction_of_test= regr.predict(testing_data)

ValueError: could not convert string to float: 'Oil-importing countries'